### PR TITLE
use the unittest module; refactor a bit for better readability

### PR DESCRIPTION
**Pull request by dshahbaz**
Started playing with demumble, noticed the unittest needed some cleanup, so I touched it up a bit.

Thanks!

### CODE REVIEW

**Comment by nico** [comment]
Cool, thanks for the patch! I didn't use unittest it's not really used that way (normally you'd have many testFoo() things each testing a specific thing) and it's 30% less code. What's the advantage of using unittest? Nice output when something fails?

**Comment by dshahbaz** [comment]
Nice output is one advantage, but more importantly it gives the test an idiomatic, standardized structure. The old version is a bit unstructured and harder to read.

**Comment by dshahbaz** [comment]
ping?

**Comment by nico** [comment]
I like the lhs code better -- it's shorter and does the same thing.

**Comment by dshahbaz** [comment]
"it's 30% shorter" is never a metric I've heard about for code quality or readability. i'd argue it's less clear and less idiomatic python, but eh, not my project anyway.

i'll close this PR.

thanks!

**Pull request closed without merging**
