### PR TITLE
Package into python library

### PR DESCRIPTION
**Pull request by stevemk14ebr**
This packages the entire library into a proper python .whl that may be uploaded to pypi or devpi. To use just do `import demumble` then `demumble.version()` for example.

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
This already incorporates the updated llvm sources from the RTTI upstream work you did.

**Comment by nico** [comment]
Hello! Thanks for the pull request, but maybe you can understand that I'm not entirely excited about a change that as far as I can tell:

- Removes the ability to build demumble for mac, linux, win all on a single mac host
- Deletes the test suite
- Reorders where all files are

Maybe you can explain what problem you're trying to solve first? Do you want to demangle symbols from Python? If so, does just shelling out to demumble via the `subprocess` api work?

**Comment by stevemk14ebr** [comment]
I can easily add the tests back. The build scripts can also be updated to follow your build preferences, I followed the typical deployment for win & linux host's. I don't have Mac so I can't build for that. The reason this was done is to make the 'library' easier to use within larger projects. Where I use it we have a virtualenv which tracks which binaries to include in the larger project whl. Whithout demumble itself being a whl I have to jump through hoops to build and get the dependencies of demumble included. It's just generally annoying from the python world to work with something that is not a package. With this work demumble would also be trivially installable from pypi which would be great for exposure and use. I think we can fix the things you have concerns about. From the python side this is a much more convenient library to work with now.

**Comment by nico** [comment]
I don't want his part of this repository. If there are small changes I can make to make it easier to have a python module wrapping this in some other repo, I'm happy to do that.

**Pull request closed without merging**
